package com.burito.enums;

public enum ErrorCode {
  INVALID_RESTAURANT_ID, INVALID_CREDENTIALS, EMAIL_ALREADY_EXISTS, INVALID_PASSWORD, USERNAME_NOT_FOUND, RESTAURANT_NOT_FOUND, INVALID_REFRESH_TOKEN
}
