package com.burito.enums;

public enum ErrorCode {
  INVALID_RESTAURANT_ID, INVALID_CREDENTIALS, EMAIL_ALREADY_EXISTS, INVALID_PASSWORD, USERNAME_NOT_FOUND, RESTAURANT_NOT_FOUND, INVALID_REFRESH_TOKEN, INVALID_CUISINE_TYPE, MENU_ITEM_NOT_FOUND, MENU_ITEM_UNAVAILABLE, CART_ITEM_NOT_FOUND
}
